### ISSUE TITLE
g920p - Touchscreen not working

### ISSUE THREAD

**Issue by nilesandstuff** [TeamNexus/issues#38]
#### Description
Touchscreen doesnt work. Probably kernel issue right?

1. Wiped cache, system, and data in twrp (twrp-3.1.1-0 most recent version for g920p)
2. Flashed LineageOS-15.0-zerofltexx-2017-09-06_1931... One of the first lines in print was "file_contexts not found" but other than that, installation completed with not issues.
3.Flashed open_gapps-arm64-8.0-pico-20170906-UNOFFICIAL.zip... No issues.
4. Flashed magisk v14.0. One of the first lines said "System installed root detected: Mount rw :(" Otherwise, magisk appeared to install normally
5. Reboot to system. Took about 10 minutes to boot up, seems normal.
6. Upon boot, I see the start screen for setting up "new" phone with the google "G" logo. Cannot tap anything. Power button works. Volume keys work. Cant tell if home button works, but it wont wake screen. Randomly the "vision settings" button in the bottom right of the screen gets highlighted somehow (as if its being partially tapped, but it never opens)... does not coincide with the timing or location of my taps.

Attempts to solve:
Wipe data, system, and cache and flash again.
Flash without wiping partitions from previous attempt at flashing lineageOS-15.0
Flash latest Skyhigh kernel port for g920p by tdhite. Kernel is for stock nougat roms, so unsurpsingly, phone wouldnt even boot with skyhigh installed.

#### Device
Samsung Galaxy S6 SM-G920P (Carrier: Sprint) (U.S. Exynos variant)

#### Used build
LineageOS-15.0-zerofltexx-2017-09-06_1931

**Comment by Lukas0610** [comment]
Unfortunately I can't support other models and variants than G920F because I just own that single device. If I have time, I may look into the differences between G and P and publish a separate kernel, but as I said, only if I have the time to do so

**Comment by sveni83** [comment]
Hello
First of all thanks for the orio.
I have the same problem with the G925f.
Only the menu and back button are displayed when starting or they flash alternately.
From the running system, however, neither lighting nor reactions are to be noted.
then I have a big problem.
after the first stand by or press the powerbutton the display gets when re-awakening an overload .. on the one hand from the light which is on the stop and synonymous of the graphics.
all too bright and only very vague to recognize.
can be repaired with a reboot but occurs at standby always on.

I'll do it all over again now because I can not work with it that way.
but I would be happy if it could be edited.

Thank you

Best regards

sven
