### ISSUE TITLE
F-droid" Error 0: null

### ISSUE THREAD

**Issue by seekr** [TeamNexus/issues#53]
#### Steps for a proper issue
[ ] **Report issues only from latest build**
[ ] Create and append bugreport from the "The Nexus"-app
[ ] Proper title
[ ] Proper description

#### Description
I try to update F-droid and as soon as it  finishes downloading the file I get a popup "Error installing F-droid" Error 0: null.

This is a clean install, the only thing I installed since flashing is Aptoide to see if the f-droid error also happened in Aptoide (it doesn't).

PS. Settings and Substratum also crash regularly, wonder if this is related. "System UI has stopped"

#### Device
Samsung Galaxy S6 SM-G920F with TWRP. Clean flash. I get "kernel is not seandroid enforcing" on boot, but seems to run fine.

#### Used build
LineageOS-8.0.0-zerofltexx-2017-10-18_0733.zip

**Comment by bugtrapper** [comment]
It's a buggy version of F-Droid's root extension included with LineageOS. It's a privileged app, so you can't update or remove it. Since it's not a system app, the /system/app-mover can't help, either.
The way I solved it was using TWRPs file manager to straight up delete f-droid and it's extension from /system/priv-app and then installing the newest version of F-Droid. It worked fine for me, but I'm no dev and not affiliated with Team Nexus, so don't take it as an official solution.

Edit: Don't forget that you have to mount the system partition first. Per default, it's not mounted in TWRP.
